import random

CHAOS = {
    1: "Your shoes are now filled with jelly. Deal with it.",
    2: "You suddenly forget how to blink for the next minute.",
    3: "A random sock appears in your hand. It smells terrible.",
    4: "Your voice changes to that of a duck for the next hour.",
    5: "You feel an intense urge to dance uncontrollably.",
    6: "All text you read is upside down for the next 10 minutes.",
    7: "You grow an extra thumb on your left hand for the next hour.",
    8: "Your hair turns bright green and stands on end.",
    9: "A chicken follows you around, clucking loudly.",
    10: "Everything you touch turns into marshmallows for the next minute.",
    11: "You randomly start speaking in rhymes.",
    12: "You hear ominous whispers whenever you’re alone.",
    13: "You can only walk backwards for the next 10 minutes.",
    14: "You sneeze glitter for the next hour.",
    15: "Your skin turns bright purple for the next 10 minutes.",
    16: "You gain the uncontrollable urge to shout ‘BOOM’ every few minutes.",
    17: "Your reflection in mirrors starts making faces at you.",
    18: "You can’t stop humming a catchy tune for the next hour.",
    19: "You forget your own name for the next minute.",
    20: "Your pockets are filled with confetti. You don’t know how it got there.",
    21: "Everything tastes like chocolate, but only to you.",
    22: "A random item from your inventory disappears, replaced by a rubber chicken.",
    23: "You feel as if someone is constantly tapping your shoulder.",
    24: "Your hands turn into flippers for the next 10 minutes.",
    25: "You become incredibly magnetic, attracting small metal objects.",
    26: "You gain the ability to speak with insects, but they’re very rude.",
    27: "Your nose grows an inch longer, Pinocchio-style.",
    28: "You hear random, distant laughter for no apparent reason.",
    29: "You grow a magnificent mustache, regardless of gender.",
    30: "Your shoes make loud squeaking noises with every step.",
    31: "You swap voices with the nearest person.",
    32: "Everything you say sounds sarcastic, even when you’re not.",
    33: "Your shadow begins to move independently of you.",
    34: "Your teeth glow in the dark for the next hour.",
    35: "You can only communicate by singing for the next 10 minutes.",
    36: "You gain the uncontrollable urge to juggle any objects you hold.",
    37: "You start seeing everything in black and white.",
    38: "You grow a third eye in the middle of your forehead for an hour.",
    39: "You feel the need to narrate everything you do out loud.",
    40: "All liquids you drink taste like orange juice, regardless of what they are.",
    41: "A random flower sprouts from the top of your head.",
    42: "You hear music wherever you go, but no one else can hear it.",
    43: "Your ears grow to twice their normal size.",
    44: "You float a few inches above the ground when you walk.",
    45: "Your laughter becomes highly contagious to others.",
    46: "You gain a random phobia for the next hour.",
    47: "Your fingernails glow bright neon colors.",
    48: "You can only speak in questions for the next 5 minutes.",
    49: "You become incredibly ticklish, even from the slightest touch.",
    50: "You feel as if you’re being watched, but there’s no one there.",
    51: "Your clothes change color every 5 minutes.",
    52: "You grow feathers on your arms.",
    53: "Your sneeze sounds like a trumpet blast.",
    54: "All food tastes like cardboard for the next 10 minutes.",
    55: "You randomly teleport 10 feet in a random direction.",
    56: "You can only whisper for the next hour.",
    57: "You become convinced that gravity is about to stop working.",
    58: "You suddenly know how to play the accordion, but don’t have one.",
    59: "Your hair grows several inches longer instantly.",
    60: "You become invisible to mirrors for the next hour.",
    61: "You feel like you're constantly standing on a moving ship.",
    62: "You develop a strange craving for pickles.",
    63: "Your head feels like it's on fire, but it's not.",
    64: "You lose your sense of balance for the next 5 minutes.",
    65: "All objects feel sticky to you, but only you.",
    66: "Your ears start twitching uncontrollably.",
    67: "You become unable to perceive the color blue.",
    68: "You start hiccuping bubbles.",
    69: "Your voice echoes loudly, even in small rooms.",
    70: "You can only walk on tiptoes for the next hour.",
    71: "Your hands are suddenly covered in glitter.",
    72: "You can hear dogs barking from miles away.",
    73: "You develop an irrational fear of spoons.",
    74: "You gain the ability to talk to plants, but they only gossip.",
    75: "Your shoes are now 3 sizes too large.",
    76: "You hear everything as if it's underwater.",
    77: "Your head spins 360 degrees, but you feel fine.",
    78: "You grow a small set of wings, but they don't work.",
    79: "Your skin feels like it’s made of rubber.",
    80: "You feel an intense need to count every step you take.",
    81: "Your shadow becomes rainbow-colored.",
    82: "You smell like fresh-baked cookies.",
    83: "You start talking in your sleep, even when you're awake.",
    84: "You see everyone around you as if they were cartoon characters.",
    85: "Your reflection in mirrors gives you advice.",
    86: "You feel like you’re walking through molasses.",
    87: "You can’t stop snapping your fingers.",
    88: "You grow a tail, but it has a mind of its own.",
    89: "Your voice becomes impossibly deep.",
    90: "You become convinced that your name is something entirely different.",
    91: "You see random words floating in the air around you.",
    92: "You feel as if your hands are constantly vibrating.",
    93: "You randomly switch languages for the next 10 minutes.",
    94: "You gain the ability to speak in rhyme effortlessly.",
    95: "Your footsteps sound like thunderclaps.",
    96: "You feel as if your arms are too short.",
    97: "You hear voices arguing in a language you don’t understand.",
    98: "You can’t recognize faces for the next hour.",
    99: "Your hair becomes incredibly static and sticks out everywhere.",
    100: "You can taste colors and see sounds."
}

def chaos(bot):
    @bot.command()
    async def chaos(ctx):
        result = random.randint(1, 100)
        answer = CHAOS[result]
        user = ctx.author
        mention = user.mention
        send_text = f'||{result}|| {mention}, you disturbed the order of the weaves of magic:\n> {answer}'
        await ctx.send(send_text)
