SKILL = {
    "str": "Strength",
    "stärke": "Strength",
    "strength": "Strength",
    "ges": "Dexterity",
    "geschicklichkeit": "Dexterity",
    "dex": "Dexterity",
    "dexterity": "Dexterity",
    "kon": "Constitution",
    "con": "Constitution",
    "konstitution": "Constitution",
    "constitution": "Constitution",
    "konsti": "Constitution",
    "int": "Intelligenz",
    "intelligence": "Intelligenz",
    "intelligenz": "Intelligenz",
    "wis": "Wisdom",
    "wisdom": "Wisdom",
    "weisheit": "Wisdom",
    "wei": "Wisdom",
    "charisma": "Charisma",
    "cha": "Charisma",
}

ATTRIBUTE = {
    "initiative": "Initiative",
    "ini": "Initiative",
    "init": "Initiative",
    "akrobatik": "Acrobatics",
    "acrobatics": "Acrobatics",
    "tier": "Animal Handling",
    "animal": "Animal Handling",
    "animalhandling": "Animal Handling",
    "arkana": "Arcana",
    "arcana": "Arcana",
    "athletik": "Athletics",
    "athletics": "Athletics",
    "täuschen": "Deception",
    "deception": "Deception",
    "geschichte": "History",
    "history": "History",
    "motiv": "Insight",
    "insight": "Insight",
    "einschüchtern": "Intimidation",
    "intimidation": "Intimidation",
    "nachforschen": "Investigation",
    "nachforschung": "Investigation",
    "investigation": "Investigation",
    "heilkunde": "Medicine",
    "medicine": "Medicine",
    "naturkunde": "Nature",
    "nature": "Nature",
    "wahrnehmung": "Perception",
    "perception": "Perception",
    "auftreten": "Performance",
    "performance": "Performance",
    "überzeugen": "Persuasion",
    "persuasion": "Persuasion",
    "religion": "Religion",
    "fingerfertigkeit": "Sleight of Hand",
    "finger": "Sleight of Hand",
    "sleight": "Sleight of Hand",
    "heimlichkeit": "Stealth",
    "stealth": "Stealth",
    "überleben": "Survival",
    "survival": "Survival",
}

PROFICIENCY = {
    "alchemist": "Alchemistkit",
    "alchemy": "Alchemistkit",
    "thieves": "Thieves Cant",
    "dieb": "Thieves Cant",
    "kaligraphie": "Calygraphykit",
    "calycraphy": "Calygraphykit",
    "schmied": "Smithing Tools",
    "smith": "Smithing Tools",
    "koch": "Cooking Tools",
    "cooking": "Cooking Tools",
    "tinker": "Tinker Tools",
    "tüftler": "Tinker Tools",
    "navigator": "Navigator",
    "vehicles": "Vehicles",
    "heilkräuter": "Herbalismkit",
    "herbalism": "Herbalismkit",
}
