WEAPON = {
    'unarmed'|'waffenlos' : "Unarmed Strike",
    'longsword'|'langschwert' : "Longsword",
    'club'|'knüppel' : "Club",
    'dagger'|'dolch' : "Dagger",
    'greatclub'|'großerknüppel' : "Greatclub",
    'handaxe'|'beil' : "Handaxe",
    'javelin'|'wurfspeer' : "Javelin",
    'hammer' : "Hammer",
    'mace'|'streitkolben' : "Mace",
    'quarterstaff'|'kampfstab': "Quarterstaff",
    'sickle'|'sichel' : "Sickle",
    'spear'|'speer' : "Spear",
    'crossbow'|'armbrust' : "Crossbow",
    'dart' : "Dart",
    'shortbow'|'kurzbogen' : "Shortbow",
    'sling'|'schleuder' : "Sling",
    'battleaxe'|'streitaxt' : "Battleaxe",
    'flail'|'flegel' : "Flail",
    'glaive'|'gleve' : "Glaive",
    'greataxe'|'zweihandaxt' : "Greataxe",
    'greatsword'|'zweihandschwert' : "Greatsword",
    'halberd'|'hellebarde' : "Halberd",
    'lance'|'lanze' : "Lance",
    'maul' : "Maul",
    'morningstar'|'morgenstern' : "Morningstar",
    'pike' : "Pike",
    'rapier' : "Rapier",
    'scimitar'|'säbel'|'krummsäbel' : "Scimitar",
    'shortsword'|'kurzschwert' : "Shortsword",
    'trident'|'dreizack' : "Trident",
    'warpick'|'kriegshacke' : "Warpick",
    'warhammer'|'kriegshammer'|'zweihandhammer' : "Warhammer",
    'whip'|'peitsche' : "Whip",
    'blowgun'|'blasrohr' : "Blowgun",
    'handcrossbow'|'handarmbrust' : "Hand Crossbow",
    'heavycrossbow'|'schwerearmbrust' : "Heavy Crossbow",
    'longbow'|'langbogen' : "Longbow",
    'net'|'netz' : "Net",
    'katana' : "Katana",
}