import commandsHandler


WEAPON = {
    'unarmed': "Unarmed Strike",
    'waffenlos': "Unarmed Strike",
    'longsword': "Longsword",
    'langschwert': "Longsword",
    'club': "Club",
    'knüppel': "Club",
    'dagger': "Dagger",
    'dolch': "Dagger",
    'greatclub': "Greatclub",
    'großerknüppel': "Greatclub",
    'handaxe': "Handaxe",
    'beil': "Handaxe",
    'javelin': "Javelin",
    'wurfspeer': "Javelin",
    'hammer': "Hammer",
    'mace': "Mace",
    'streitkolben': "Mace",
    'quarterstaff': "Quarterstaff",
    'kampfstab': "Quarterstaff",
    'sickle': "Sickle",
    'sichel': "Sickle",
    'spear': "Spear",
    'speer': "Spear",
    'crossbow': "Crossbow",
    'armbrust': "Crossbow",
    'dart': "Dart",
    'shortbow': "Shortbow",
    'kurzbogen': "Shortbow",
    'sling': "Sling",
    'schleuder': "Sling",
    'battleaxe': "Battleaxe",
    'streitaxt': "Battleaxe",
    'flail': "Flail",
    'flegel': "Flail",
    'glaive': "Glaive",
    'gleve': "Glaive",
    'greataxe': "Greataxe",
    'zweihandaxt': "Greataxe",
    'greatsword': "Greatsword",
    'zweihandschwert': "Greatsword",
    'halberd': "Halberd",
    'hellebarde': "Halberd",
    'lance': "Lance",
    'lanze': "Lance",
    'maul': "Maul",
    'morningstar': "Morningstar",
    'morgenstern': "Morningstar",
    'pike': "Pike",
    'rapier': "Rapier",
    'scimitar': "Scimitar",
    'säbel': "Scimitar",
    'krummsäbel': "Scimitar",
    'shortsword': "Shortsword",
    'kurzschwert': "Shortsword",
    'trident': "Trident",
    'dreizack': "Trident",
    'warpick': "Warpick",
    'kriegshacke': "Warpick",
    'warhammer': "Warhammer",
    'kriegshammer': "Warhammer",
    'zweihandhammer': "Warhammer",
    'whip': "Whip",
    'peitsche': "Whip",
    'blowgun': "Blowgun",
    'blasrohr': "Blowgun",
    'handcrossbow': "Hand Crossbow",
    'handarmbrust': "Hand Crossbow",
    'heavycrossbow': "Heavy Crossbow",
    'schwerearmbrust': "Heavy Crossbow",
    'longbow': "Longbow",
    'langbogen': "Longbow",
    'net': "Net",
    'netz': "Net",
    'katana': "Katana",
}

def addWeaponRolls(bot):
    for weapon_input, weapon_name in WEAPON.items():
        @bot.command(name=weapon_input)
        async def weapon(ctx, *args, weapon_name=weapon_name):
            extra = " ".join(args)
            user = ctx.author
            await ctx.send(commandsHandler.weaponRoll(weapon_name, extra, user))